- hosts: all
  tasks:

    - name: get customized fzf repo
      git:
        repo: https://github.com/jan-warchol/fzf
        dest: "{{ fzf_home }}"

    - name: add upstream to fzf repo
      blockinfile:
        block: |
          [remote "upstream"]
                  url = https://github.com/junegunn/fzf.git
                  fetch = +refs/heads/*:refs/remotes/upstream/*
        dest: "{{ fzf_home }}/.git/config"

    - name: download fzf binary
      shell: "{{ fzf_home }}/install --bin"
      args:
        creates: "{{ fzf_home }}/bin/fzf"

    - name: ensure directories exist
      file:
        dest: "{{ ansible_env.HOME }}/data/fzf/"
        state: directory
        mode: 0700

    - name: ensure fzf history file exists
      copy:
        dest: "{{ fzf_history }}"
        content: ""
        force: no
